### ISSUE TITLE
Unhide --no-package-symlinks flag

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1340]
Currently this implemented, but hidden.

Related to https://github.com/dart-lang/pub/issues/727

**Comment by nex3** [comment]
For background, we're waiting on doing this until we're reasonably confident that it's possible to rewrite all code that worked with `packages/` directories to work with package specs instead. Currently this is blocked on:

- [ ] dart-lang/sdk#23951 so that applications can spawn isolates with different package specs than the parent.
- [ ] dart-lang/sdk#24524 so that applications can spawn Dart subprocesses with the same package spec as the parent.
- [ ] dart-lang/test#327 as a proof-of-concept that an application that uses package roots/isolate spawning heavily can run without symlinks.

**Comment by mit-mit** [comment]
Yes, to meet the original goals of 1.13 we need to get this exposed so that externals can confidently test if their tools work without a package dir so that we in return can flip the default in 1.14.

**Comment by nex3** [comment]
This may or may not be done by 1.13. In addition to the two SDK blockers that have yet to be fixed, the issues blocking dart-lang/test#327 were resolved a lot later than expected. It'll probably take a couple weeks to get `test` running without symlinks even if we don't encounter any additional features we need. Once that's done we can switch on `--no-packages-dir` on dev, but I'll want a couple weeks before release to get real-world user data and make sure there aren't any lingering issues that I didn't run into myself.

**Comment by mit-mit** [comment]
@nex3 anything else we need here? How do you suggest we roll this out?

**Comment by mit-mit** [comment]
We just experimented a bit; the flag is there, it's just not mentioned in help. So I guess there is enough that we can ask those that depend on the symlinks to try running pub with this flag, and then use the .packages file?

**Comment by nex3** [comment]
I'm not planning to make the flag visible for 1.14. The flag shouldn't be visible until we're very confident that users can in practice update their existing packages to run without packages/ directories. I plan to convert pub and the test package as a proof-of-concept, but that work won't be done in time for the upcoming release—and if the feedback from that work necessitates changes in the APIs, there certainly won't be time to adjust them.

**Comment by kevmoo** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/24093 – which is part of https://github.com/dart-lang/sdk/issues/24112

**Comment by mit-mit** [comment]
https://github.com/dart-lang/sdk/issues/24093 is done, let go ahead and make this change, please.

**Comment by nex3** [comment]
I'm still waiting on snapshot tests as well.

**Comment by zoechi** [comment]
should #24288 be updated/closed as well?

**Comment by kevmoo** [comment]
> should dart-lang/sdk#24288 be updated/closed as well?

Nope. We're going to flip the default from opt-out to opt-in (for creating directories).
