### ISSUE TITLE
deprecate `pub` command

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2736]
Things to do:
 * [x] Migrate `flutter pub` to not wrap `pub`, but `dart pub` instead.
 * [ ] Migrate [travis-ci scripts][1] to use `dart pub get` (for `dart >= 2.10.0`) (wontfix for now)
 * [x] [Dart-Code#2944][3] Migrate vscode integration to use `dart pub get` (for `dart >= 2.10.0`) 
 * [x] [WEB-48176][2]: Migrate intelij integration to use `dart pub get` (for `dart >= 2.10.0`),
 * [x] Migrate `pana` to invoke through `dart pub` (https://github.com/dart-lang/pana/issues/852)
 * [x] Migrate `pub-dev` to use `dart pub` (https://github.com/dart-lang/pub-dev/issues/4655)
 * [x] Add deprecation warning when `pub` is invoked in a terminal.
 * [x] Change `pub` to be a wrapper around `dart pub`.

[1]: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/dart.rb#L169
[2]: https://youtrack.jetbrains.com/issue/WEB-48176
[3]: https://github.com/Dart-Code/Dart-Code/issues/2944

**Comment by sigurdm** [comment]
Migrate flutter pub to not wrap `pub`, but `dart pub` instead.

We probably want to wrap `dart --disable-dartdev-analytics pub` instead, so we don't send analytics twice.

**Comment by sigurdm** [comment]
>  Migrate travis-ci scripts to use dart pub get (for dart >= 2.10.0)
Do we still need this after migrating to github code actions?

**Comment by jonasfj** [comment]
note to self, patching travis involves:
 * https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/dart.rb
 * https://github.com/travis-ci/travis-build (which can create a shell script from a `travis.yaml` file)

**Comment by mit-mit** [comment]
@sigurdm can this be closed now?

**Comment by sigurdm** [comment]
I managed to commit out of order - we can close whenever: https://github.com/flutter/flutter/pull/88509 lands. I hope to land it before flutter discovers that the sdk is broken for them :|
