### ISSUE TITLE
[meta] Aligning 'flutter pub' and 'dart pub' behavior

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2971]
* [ ] Run `dart pub get` for `example/` when running `dart pub get` in root project.
 * [ ] Trigger a hook for flutter plugin generation when `FLUTTER_ROOT` is present, and root package have a flutter dependency.
 * [ ] Improve HTTP retry logic to recover from broken TCP connections
 * [ ] Validate content hash for downloaded files (https://github.com/dart-lang/pub/issues/2281)
 * [x] Support running `dart pub -C <folder>` where `<folder>` is used instead of CWD (https://github.com/dart-lang/pub/pull/2876)
 * [ ] Refactor `flutter pub get` to use [`inheritStdio`](https://api.dart.dev/stable/2.12.4/dart-io/ProcessStartMode/inheritStdio-constant.html) and fix tests
 * [ ] Implement metrics collection for better popularity metrics (https://github.com/dart-lang/pub/pull/2778)
 * [ ] Resolve location of `PUB_CACHE` whether it should be a global cache for Flutter SDK too.

**Comment by jonasfj** [comment]
Looks like there is some movement on migrating Flutter away from using a custom `PUB_CACHE` in https://github.com/flutter/flutter/issues/53833.

**Comment by sigurdm** [comment]
I believe the cache alignment happened in: https://github.com/flutter/flutter/pull/105343 checking that off.
